### ISSUE TITLE
Update to charter proposal

### ISSUE THREAD

**Issue by nicholascar** [RDAProvPatWG/minutes#1]
1. Update Adoption and Engagement section texts per September 22 discussions.
2. Update discussion of deliverables.
3. Merge P10 Revision into Main branch.
4. Submit to RDA

**Comment by ddubin65** [comment]
The update has been submitted to TAB.
https://github.com/RDAProvIG/WGplanning/commit/e5ff69342ca2fbbc4d40419f684470ef9641ab91
