### ISSUE TITLE
Send Patterns 12, 25 & 26 to Ted Habermann for review

### ISSUE THREAD

**Issue by nicholascar** [RDAProvPatWG/minutes#7]
for Ivana Ivanova

**Comment by i2vana** [comment]
done - sent an email to Ted Habermann (Nick, please repair Ted's surname in the minutes) on 10 Nov 2017 inviting him to review all patterns in the DB, expecting his interest in the three ISO 19100 related patterns specifically. Waiting for Ted's response..
